title: "Wanru Guo"
description: "Oncology statistician working in biostatistics, machine learning, genomics, and real-world evidence."
theme: minima
plugins:
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM

url: "https://wguo3773.github.io"

